### PR TITLE
reduce amount of drawing in file_manager to improve performance

### PR DESCRIPTION
**Pull request by Emily**
When I first pulled down Redox to play with it, the very first thing I noticed was how slow `file_manager` responded when in the `/bin` directory. I figured it might be a good first step to investigate why. It turns out that every redraw would draw the entire window, rather than just the portions that changed.

The main change here is that when redrawing to move the highlight around, it now only redraws the two affected rows: the previously lit row, and the newly lit row. Now you can now move the mouse around really fast and not have the highlighting lag behind.

I feel like a lot of the code that makes up `file_manager` would be at home in `orbtk`, I'd be interested in following this PR up by making the necessary widgets there, and porting `file_manager` over. It looks like `Grid` is almost what's needed, so perhaps not too much would actually need to be done in `orbtk`.

### CODE REVIEW

**Comment by Emily** [comment]
Fixing the conflict currently... happened between rebasing on upstream and writing the PR. :)

**Comment by jackpot51** [comment]
This is a very good change. Sorry about changing things in master so often.

 `file_manager` was one of the first applications I wrote, and that was before `orbtk` existed. I hope it can utilize `orbtk` in the future!

**Comment by jackpot51** [comment]
This issue will be fixed when this change is merged: https://github.com/redox-os/redox/issues/809

**Comment by jackpot51** [comment]
I merged the change - conflicts were resolved and I tested it - much better performance in `/bin`!

**Pull request merged**
